
import java.awt.Component;
import java.awt.Container;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.JButton;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Tahwela extends javax.swing.JFrame {

    static LoginForm frame;

    public Tahwela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        takhtet_jCheckBox7 = new javax.swing.JCheckBox();
        mogam_jCheckBox6 = new javax.swing.JCheckBox();
        amn_jCheckBox5 = new javax.swing.JCheckBox();
        tagned_jCheckBox3 = new javax.swing.JCheckBox();
        komesuon_jCheckBox4 = new javax.swing.JCheckBox();
        afrad_jCheckBox2 = new javax.swing.JCheckBox();
        nozom_jCheckBox9 = new javax.swing.JCheckBox();
        fax_jButton1 = new javax.swing.JButton();
        mokatba_jButton2 = new javax.swing.JButton();
        send_jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("منظومه فاكسات التحويله");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 150));
        setName(""); // NOI18N
        setResizable(false);

        takhtet_jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        takhtet_jCheckBox7.setText("التخطيط");

        mogam_jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mogam_jCheckBox6.setText("المجمع");

        amn_jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        amn_jCheckBox5.setText("الامن");

        tagned_jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tagned_jCheckBox3.setText("التجنيد");

        komesuon_jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        komesuon_jCheckBox4.setText("القومسيون");

        afrad_jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        afrad_jCheckBox2.setText("الافراد");

        nozom_jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nozom_jCheckBox9.setText("النظم");

        fax_jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fax_jButton1.setActionCommand("إختيار الفاكس");
        fax_jButton1.setLabel("إختيار الفاكس");
        fax_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fax_jButton1ActionPerformed(evt);
            }
        });

        mokatba_jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mokatba_jButton2.setText("إختيار المكاتبه");
        mokatba_jButton2.setActionCommand("");
        mokatba_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mokatba_jButton2ActionPerformed(evt);
            }
        });

        send_jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        send_jButton3.setText("إرسال");
        send_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mogam_jCheckBox6)
                            .addComponent(tagned_jCheckBox3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(afrad_jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nozom_jCheckBox9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(amn_jCheckBox5))
                                    .addComponent(takhtet_jCheckBox7))
                                .addGap(121, 121, 121)
                                .addComponent(komesuon_jCheckBox4)))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(send_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(mokatba_jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(fax_jButton1)))
                        .addGap(39, 44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nozom_jCheckBox9)
                    .addComponent(afrad_jCheckBox2)
                    .addComponent(mogam_jCheckBox6))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(komesuon_jCheckBox4)
                    .addComponent(takhtet_jCheckBox7)
                    .addComponent(tagned_jCheckBox3))
                .addGap(39, 39, 39)
                .addComponent(amn_jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mokatba_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fax_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String filenameFax;
    String filenameMokatba;

    ArrayList<String> pathList = new ArrayList<>();

    // complete this function
    private void saveAfroa() {

        if (nozom_jCheckBox9.isSelected()) {
            pathList.add("النظم");
        }

        if (afrad_jCheckBox2.isSelected()) {
            pathList.add("الافراد");
        }

        if (amn_jCheckBox5.isSelected()) {
            pathList.add("الامن");
        }

        if (komesuon_jCheckBox4.isSelected()) {
            pathList.add("القومسيون");
        }

        if (mogam_jCheckBox6.isSelected()) {
            pathList.add("المجمع");
        }

        if (tagned_jCheckBox3.isSelected()) {
            pathList.add("التجنيد");
        }

        if (takhtet_jCheckBox7.isSelected()) {
            pathList.add("التخطيط");
        }

    }

    // complete this function
    private void removeAfroa() {

        nozom_jCheckBox9.setSelected(false);

        afrad_jCheckBox2.setSelected(false);

        amn_jCheckBox5.setSelected(false);

        komesuon_jCheckBox4.setSelected(false);

        mogam_jCheckBox6.setSelected(false);

        tagned_jCheckBox3.setSelected(false);

        takhtet_jCheckBox7.setSelected(false);
    }

    private LocalDate getCurrentDate() {
        LocalDate date = LocalDate.now();
        return date;
    }

    // replace destinationPath inside filechooser
    public Path choose(String type) {

        JFileChooser choose = new JFileChooser("d:");

        // JFileChooser j = new JFileChooser(new File("C:\\Users\\pc\\Documents\\New folder\\"));
        choose.setFileFilter(new FileNameExtensionFilter("PDF", "pdf"));

        disableButton(choose, "FileChooser.homeFolderIcon");
        disableButton(choose, "FileChooser.newFolderIcon");

        choose.showDialog(null, "إرسال " + type);

        Path sourcePath = choose.getSelectedFile().toPath();

        return sourcePath;
    }

    public void disableButton(final Container c, final String iconString) {

        int len = c.getComponentCount();
        for (int i = 0; i < len; i++) {
            Component comp = c.getComponent(i);
            if (comp instanceof JButton) {
                JButton b = (JButton) comp;
                Icon icon = b.getIcon();
                if (icon != null
                        && icon == UIManager.getIcon(iconString)) {
                    b.setEnabled(false);
                }
            } else if (comp instanceof Container) {
                disableButton((Container) comp, iconString);
            }
        }
    }

    public void copy(Path sourcePath, Path destinationPath) {
        try {

            Files.copy(sourcePath, destinationPath);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(1);
        }
    }

    // replace destinationPath
    private void saveFax() {

        Path sourcePath = choose("الفاكس");

        filenameFax = sourcePath.getFileName().toString();

        Path destinationPath = Paths.get("D:\\faxat\\التحويله\\فاكسات\\" + filenameFax);

        copy(sourcePath, destinationPath);
    }

    // replace destinationPath
    private void saveMokatba() {

        Path sourcePath = choose("المكاتبه");

        filenameMokatba = sourcePath.getFileName().toString();

        Path destinationPath = Paths.get("D:\\faxat\\التحويله\\مكاتبات\\" + filenameMokatba);

        copy(sourcePath, destinationPath);
    }

    // replace destinationPath and sourcePath
    private void sendFaxat() {

        Path sourcePath = Paths.get("D:\\faxat\\التحويله\\فاكسات\\" + filenameFax);

        int day = getCurrentDate().getDayOfMonth();
        int month = getCurrentDate().getMonthValue();

        try {

            for (String afroaName : pathList) {

                Path destinationPath = Paths.get("D:\\faxat\\الافرع\\" + afroaName + "\\" + month + "\\" + day + "\\فاكسات\\" + filenameFax);

                Files.copy(sourcePath, destinationPath);
            }

            Files.delete(sourcePath);

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    // replace destinationPath and sourcePath
    private void sendMokatbat() {

        Path sourcePath = Paths.get("D:\\faxat\\التحويله\\مكاتبات\\" + filenameMokatba);

        int day = getCurrentDate().getDayOfMonth();
        int month = getCurrentDate().getMonthValue();

        try {

            for (String afroaName : pathList) {

                Path destinationPath = Paths.get("D:\\faxat\\الافرع\\" + afroaName + "\\" + month + "\\" + day + "\\مكاتبات\\" + filenameMokatba);

                Files.copy(sourcePath, destinationPath);
            }

            Files.delete(sourcePath);

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void fax_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fax_jButton1ActionPerformed

        saveFax();

    }//GEN-LAST:event_fax_jButton1ActionPerformed

    private void mokatba_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mokatba_jButton2ActionPerformed

        saveMokatba();

    }//GEN-LAST:event_mokatba_jButton2ActionPerformed

    private void send_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_jButton3ActionPerformed

        if (nozom_jCheckBox9.isSelected() == false
                && afrad_jCheckBox2.isSelected() == false
                && mogam_jCheckBox6.isSelected() == false
                && takhtet_jCheckBox7.isSelected() == false
                && tagned_jCheckBox3.isSelected() == false
                && komesuon_jCheckBox4.isSelected() == false
                && amn_jCheckBox5.isSelected() == false) {

            JOptionPane.showMessageDialog(this, "حدد الافرع التي تريد ارسال فاكس لها");

        } else {

            saveAfroa();

            sendFaxat();

            sendMokatbat();

            removeAfroa();

            JOptionPane.showMessageDialog(this, "تم ارسال الفاكسات الي الافرع المحدده");

        }

    }//GEN-LAST:event_send_jButton3ActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                frame = new LoginForm();
                frame.setTitle("شاشه تسجيل الدخول");
                frame.setVisible(true);
                frame.setBounds(450, 50, 370, 450);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox afrad_jCheckBox2;
    private javax.swing.JCheckBox amn_jCheckBox5;
    private javax.swing.JButton fax_jButton1;
    private javax.swing.JCheckBox komesuon_jCheckBox4;
    private javax.swing.JCheckBox mogam_jCheckBox6;
    private javax.swing.JButton mokatba_jButton2;
    private javax.swing.JCheckBox nozom_jCheckBox9;
    private javax.swing.JButton send_jButton3;
    private javax.swing.JCheckBox tagned_jCheckBox3;
    private javax.swing.JCheckBox takhtet_jCheckBox7;
    // End of variables declaration//GEN-END:variables
}
